/* ============================================================================
   LUCID — QUOTE LIBRARY
   ----------------------------------------------------------------------------
   THIS IS THE ONLY FILE YOU NEED TO EDIT TO ADD QUOTES.
   Edit it from your phone: open the repo in the GitHub app, tap this file,
   tap the pencil, add a line, commit. The site redeploys in about 40 seconds.

   Format - one object per quote:
     { t: "The quote text.", a: "Author Name", c: "category" }

   Valid categories (must match one of these exactly):
     "inspiration" - "stoic" - "humor" - "wisdom" - "creativity" - "grit"

   Rules of thumb:
     - Keep `t` under ~220 characters so it looks great on a phone.
     - Use "Unknown" for `a` if you don't know the author.
     - Don't forget the trailing comma after each } - except the very last one.

   The thinker dropdown is built from the `a` field automatically, and is
   scoped to the category you're on. To make a thinker worth filtering to,
   give them several quotes spread across a few categories.
   ========================================================================== */

window.QUOTES = [
  // -- INSPIRATION ---------------------------------------------------------
  { t: "Learn from yesterday, live for today, hope for tomorrow.", a: "Albert Einstein", c: "inspiration" },
  { t: "Happiness depends upon ourselves.", a: "Aristotle", c: "inspiration" },
  { t: "Hope is a waking dream.", a: "Aristotle", c: "inspiration" },
  { t: "Start where you are. Use what you have. Do what you can.", a: "Arthur Ashe", c: "inspiration" },
  { t: "Nothing is impossible. The word itself says 'I'm possible.'", a: "Audrey Hepburn", c: "inspiration" },
  { t: "The best time to plant a tree was twenty years ago. The second best time is now.", a: "Chinese Proverb", c: "inspiration" },
  { t: "Choose a job you love, and you will never have to work a day in your life.", a: "Confucius", c: "inspiration" },
  { t: "Everything has beauty, but not everyone sees it.", a: "Confucius", c: "inspiration" },
  { t: "Wherever you go, go with all your heart.", a: "Confucius", c: "inspiration" },
  { t: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt", c: "inspiration" },
  { t: "Light tomorrow with today.", a: "Elizabeth Barrett Browning", c: "inspiration" },
  { t: "If you want to improve, be content to be thought foolish and stupid.", a: "Epictetus", c: "inspiration" },
  { t: "Make the best use of what is in your power, and take the rest as it happens.", a: "Epictetus", c: "inspiration" },
  { t: "The only limit to our realization of tomorrow is our doubts of today.", a: "Franklin D. Roosevelt", c: "inspiration" },
  { t: "Become who you are.", a: "Friedrich Nietzsche", c: "inspiration" },
  { t: "He who would learn to fly one day must first learn to stand and walk and run and climb and dance.", a: "Friedrich Nietzsche", c: "inspiration" },
  { t: "Everything you've ever wanted is on the other side of fear.", a: "George Addair", c: "inspiration" },
  { t: "Go confidently in the direction of your dreams. Live the life you have imagined.", a: "Henry David Thoreau", c: "inspiration" },
  { t: "Whether you think you can or you think you can't, you're right.", a: "Henry Ford", c: "inspiration" },
  { t: "Someday is not a day of the week.", a: "Janet Dailey", c: "inspiration" },
  { t: "A ship in harbor is safe, but that is not what ships are built for.", a: "John A. Shedd", c: "inspiration" },
  { t: "A good traveler has no fixed plans and is not intent on arriving.", a: "Lao Tzu", c: "inspiration" },
  { t: "Be content with what you have; rejoice in the way things are.", a: "Lao Tzu", c: "inspiration" },
  { t: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", a: "Marcus Aurelius", c: "inspiration" },
  { t: "When you arise in the morning, think of what a precious privilege it is to be alive.", a: "Marcus Aurelius", c: "inspiration" },
  { t: "Keep away from people who try to belittle your ambitions.", a: "Mark Twain", c: "inspiration" },
  { t: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", a: "Mark Twain", c: "inspiration" },
  { t: "It always seems impossible until it's done.", a: "Nelson Mandela", c: "inspiration" },
  { t: "There is no passion to be found in settling for a life that is less than the one you are capable of living.", a: "Nelson Mandela", c: "inspiration" },
  { t: "Be yourself; everyone else is already taken.", a: "Oscar Wilde", c: "inspiration" },
  { t: "We are all in the gutter, but some of us are looking at the stars.", a: "Oscar Wilde", c: "inspiration" },
  { t: "Do not go where the path may lead; go instead where there is no path and leave a trail.", a: "Ralph Waldo Emerson", c: "inspiration" },
  { t: "Nothing great was ever achieved without enthusiasm.", a: "Ralph Waldo Emerson", c: "inspiration" },
  { t: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", a: "Ralph Waldo Emerson", c: "inspiration" },
  { t: "Write it on your heart that every day is the best day in the year.", a: "Ralph Waldo Emerson", c: "inspiration" },
  { t: "The garden of the world has no limits, except in your mind.", a: "Rumi", c: "inspiration" },
  { t: "What you seek is seeking you.", a: "Rumi", c: "inspiration" },
  { t: "You were born with wings. Why prefer to crawl through life?", a: "Rumi", c: "inspiration" },
  { t: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.", a: "Seneca", c: "inspiration" },
  { t: "Life is long if you know how to use it.", a: "Seneca", c: "inspiration" },
  { t: "Employ your time in improving yourself by other men's writings, so that you shall gain easily what others have labored hard for.", a: "Socrates", c: "inspiration" },
  { t: "Let him that would move the world first move himself.", a: "Socrates", c: "inspiration" },
  { t: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs", c: "inspiration" },
  { t: "Believe you can and you're halfway there.", a: "Theodore Roosevelt", c: "inspiration" },
  { t: "You miss one hundred percent of the shots you don't take.", a: "Wayne Gretzky", c: "inspiration" },
  { t: "Act as if what you do makes a difference. It does.", a: "William James", c: "inspiration" },
  { t: "What you get by achieving your goals is not as important as what you become by achieving them.", a: "Zig Ziglar", c: "inspiration" },

  // -- STOIC ---------------------------------------------------------------
  { t: "First say to yourself what you would be; and then do what you have to do.", a: "Epictetus", c: "stoic" },
  { t: "How long are you going to wait before you demand the best for yourself?", a: "Epictetus", c: "stoic" },
  { t: "It's not what happens to you, but how you react to it that matters.", a: "Epictetus", c: "stoic" },
  { t: "Man is not worried by real problems so much as by his imagined anxieties about real problems.", a: "Epictetus", c: "stoic" },
  { t: "No man is free who is not master of himself.", a: "Epictetus", c: "stoic" },
  { t: "Wealth consists not in having great possessions, but in having few wants.", a: "Epictetus", c: "stoic" },
  { t: "Confine yourself to the present.", a: "Marcus Aurelius", c: "stoic" },
  { t: "If it is not right, do not do it. If it is not true, do not say it.", a: "Marcus Aurelius", c: "stoic" },
  { t: "The happiness of your life depends upon the quality of your thoughts.", a: "Marcus Aurelius", c: "stoic" },
  { t: "The impediment to action advances action. What stands in the way becomes the way.", a: "Marcus Aurelius", c: "stoic" },
  { t: "Waste no more time arguing about what a good man should be. Be one.", a: "Marcus Aurelius", c: "stoic" },
  { t: "You have power over your mind, not outside events. Realize this, and you will find strength.", a: "Marcus Aurelius", c: "stoic" },
  { t: "Begin at once to live, and count each separate day as a separate life.", a: "Seneca", c: "stoic" },
  { t: "Difficulties strengthen the mind, as labor does the body.", a: "Seneca", c: "stoic" },
  { t: "He who fears death will never do anything worthy of a man who is alive.", a: "Seneca", c: "stoic" },
  { t: "It is not that we have a short time to live, but that we waste a lot of it.", a: "Seneca", c: "stoic" },
  { t: "Luck is what happens when preparation meets opportunity.", a: "Seneca", c: "stoic" },
  { t: "We suffer more often in imagination than in reality.", a: "Seneca", c: "stoic" },

  // -- HUMOR ---------------------------------------------------------------
  { t: "People say nothing is impossible, but I do nothing every day.", a: "A. A. Milne", c: "humor" },
  { t: "If you can't explain it simply, you don't understand it well enough.", a: "Albert Einstein", c: "humor" },
  { t: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", a: "Albert Einstein", c: "humor" },
  { t: "The gods too are fond of a joke.", a: "Aristotle", c: "humor" },
  { t: "If you think you are too small to make a difference, try sleeping with a mosquito.", a: "Dalai Lama", c: "humor" },
  { t: "Do not take life too seriously. You will never get out of it alive.", a: "Elbert Hubbard", c: "humor" },
  { t: "Without music, life would be a mistake.", a: "Friedrich Nietzsche", c: "humor" },
  { t: "I always wanted to be somebody, but now I realize I should have been more specific.", a: "Lily Tomlin", c: "humor" },
  { t: "Age is an issue of mind over matter. If you don't mind, it doesn't matter.", a: "Mark Twain", c: "humor" },
  { t: "Get your facts first, then you can distort them as you please.", a: "Mark Twain", c: "humor" },
  { t: "It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt.", a: "Mark Twain", c: "humor" },
  { t: "The reports of my death are greatly exaggerated.", a: "Mark Twain", c: "humor" },
  { t: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", a: "Mark Twain", c: "humor" },
  { t: "Always borrow money from a pessimist. He won't expect it back.", a: "Oscar Wilde", c: "humor" },
  { t: "I am so clever that sometimes I don't understand a single word of what I am saying.", a: "Oscar Wilde", c: "humor" },
  { t: "I can resist everything except temptation.", a: "Oscar Wilde", c: "humor" },
  { t: "Some cause happiness wherever they go; others whenever they go.", a: "Oscar Wilde", c: "humor" },
  { t: "The louder he talked of his honor, the faster we counted our spoons.", a: "Ralph Waldo Emerson", c: "humor" },
  { t: "I know that I am intelligent, because I know that I know nothing.", a: "Socrates", c: "humor" },
  { t: "My advice to you is get married: if you find a good wife you'll be happy; if not, you'll become a philosopher.", a: "Socrates", c: "humor" },
  { t: "A day without sunshine is like, you know, night.", a: "Steve Martin", c: "humor" },
  { t: "I'm writing a book. I've got the page numbers done.", a: "Steven Wright", c: "humor" },
  { t: "The trouble with having an open mind is that people keep coming along and sticking things into it.", a: "Terry Pratchett", c: "humor" },
  { t: "I have not failed. I've just found ten thousand ways that won't work.", a: "Thomas Edison", c: "humor" },
  { t: "The early bird gets the worm, but the second mouse gets the cheese.", a: "Unknown", c: "humor" },
  { t: "Everything is funny, as long as it's happening to somebody else.", a: "Will Rogers", c: "humor" },
  { t: "The road to success is dotted with many tempting parking spaces.", a: "Will Rogers", c: "humor" },

  // -- WISDOM --------------------------------------------------------------
  { t: "In the middle of difficulty lies opportunity.", a: "Albert Einstein", c: "wisdom" },
  { t: "The important thing is not to stop questioning.", a: "Albert Einstein", c: "wisdom" },
  { t: "Try not to become a man of success, but rather try to become a man of value.", a: "Albert Einstein", c: "wisdom" },
  { t: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", a: "Aristotle", c: "wisdom" },
  { t: "Knowing yourself is the beginning of all wisdom.", a: "Aristotle", c: "wisdom" },
  { t: "The whole is greater than the sum of its parts.", a: "Aristotle", c: "wisdom" },
  { t: "An investment in knowledge pays the best interest.", a: "Benjamin Franklin", c: "wisdom" },
  { t: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", a: "Benjamin Franklin", c: "wisdom" },
  { t: "The mind is everything. What you think you become.", a: "Buddha", c: "wisdom" },
  { t: "Before you embark on a journey of revenge, dig two graves.", a: "Confucius", c: "wisdom" },
  { t: "Real knowledge is to know the extent of one's ignorance.", a: "Confucius", c: "wisdom" },
  { t: "The man who moves a mountain begins by carrying away small stones.", a: "Confucius", c: "wisdom" },
  { t: "Only the educated are free.", a: "Epictetus", c: "wisdom" },
  { t: "We have two ears and one mouth, so that we can listen twice as much as we speak.", a: "Epictetus", c: "wisdom" },
  { t: "He who has a why to live can bear almost any how.", a: "Friedrich Nietzsche", c: "wisdom" },
  { t: "The higher we soar, the smaller we appear to those who cannot fly.", a: "Friedrich Nietzsche", c: "wisdom" },
  { t: "There are no facts, only interpretations.", a: "Friedrich Nietzsche", c: "wisdom" },
  { t: "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.", a: "Lao Tzu", c: "wisdom" },
  { t: "Nature does not hurry, yet everything is accomplished.", a: "Lao Tzu", c: "wisdom" },
  { t: "Silence is a source of great strength.", a: "Lao Tzu", c: "wisdom" },
  { t: "The journey of a thousand miles begins with a single step.", a: "Lao Tzu", c: "wisdom" },
  { t: "To attain knowledge, add things every day. To attain wisdom, subtract things every day.", a: "Lao Tzu", c: "wisdom" },
  { t: "When I let go of what I am, I become what I might be.", a: "Lao Tzu", c: "wisdom" },
  { t: "Simplicity is the ultimate sophistication.", a: "Leonardo da Vinci", c: "wisdom" },
  { t: "Be the change that you wish to see in the world.", a: "Mahatma Gandhi", c: "wisdom" },
  { t: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", a: "Marcus Aurelius", c: "wisdom" },
  { t: "The soul becomes dyed with the color of its thoughts.", a: "Marcus Aurelius", c: "wisdom" },
  { t: "Kindness is the language which the deaf can hear and the blind can see.", a: "Mark Twain", c: "wisdom" },
  { t: "The two most important days in your life are the day you are born and the day you find out why.", a: "Mark Twain", c: "wisdom" },
  { t: "Turn your wounds into wisdom.", a: "Oprah Winfrey", c: "wisdom" },
  { t: "Experience is simply the name we give our mistakes.", a: "Oscar Wilde", c: "wisdom" },
  { t: "The truth is rarely pure and never simple.", a: "Oscar Wilde", c: "wisdom" },
  { t: "The only person you are destined to become is the person you decide to be.", a: "Ralph Waldo Emerson", c: "wisdom" },
  { t: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", a: "Ralph Waldo Emerson", c: "wisdom" },
  { t: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", a: "Rumi", c: "wisdom" },
  { t: "The wound is the place where the light enters you.", a: "Rumi", c: "wisdom" },
  { t: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", a: "Rumi", c: "wisdom" },
  { t: "As long as you live, keep learning how to live.", a: "Seneca", c: "wisdom" },
  { t: "Every new beginning comes from some other beginning's end.", a: "Seneca", c: "wisdom" },
  { t: "Be as you wish to seem.", a: "Socrates", c: "wisdom" },
  { t: "The only true wisdom is in knowing you know nothing.", a: "Socrates", c: "wisdom" },
  { t: "The unexamined life is not worth living.", a: "Socrates", c: "wisdom" },
  { t: "Wonder is the beginning of wisdom.", a: "Socrates", c: "wisdom" },
  { t: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Will Durant", c: "wisdom" },

  // -- CREATIVITY ----------------------------------------------------------
  { t: "Creativity is intelligence having fun.", a: "Albert Einstein", c: "creativity" },
  { t: "Imagination is more important than knowledge.", a: "Albert Einstein", c: "creativity" },
  { t: "Logic will get you from A to B. Imagination will take you everywhere.", a: "Albert Einstein", c: "creativity" },
  { t: "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", a: "Antoine de Saint-Exupery", c: "creativity" },
  { t: "The aim of art is to represent not the outward appearance of things, but their inward significance.", a: "Aristotle", c: "creativity" },
  { t: "I hear and I forget. I see and I remember. I do and I understand.", a: "Confucius", c: "creativity" },
  { t: "The desire to create is one of the deepest yearnings of the human soul.", a: "Dieter F. Uchtdorf", c: "creativity" },
  { t: "One must still have chaos in oneself to be able to give birth to a dancing star.", a: "Friedrich Nietzsche", c: "creativity" },
  { t: "We have art in order not to die of the truth.", a: "Friedrich Nietzsche", c: "creativity" },
  { t: "You can't wait for inspiration. You have to go after it with a club.", a: "Jack London", c: "creativity" },
  { t: "Vision is the art of seeing what is invisible to others.", a: "Jonathan Swift", c: "creativity" },
  { t: "To live a creative life, we must lose our fear of being wrong.", a: "Joseph Chilton Pearce", c: "creativity" },
  { t: "Great acts are made up of small deeds.", a: "Lao Tzu", c: "creativity" },
  { t: "The usefulness of a pot comes from its emptiness.", a: "Lao Tzu", c: "creativity" },
  { t: "The secret of getting ahead is getting started.", a: "Mark Twain", c: "creativity" },
  { t: "You can't use up creativity. The more you use, the more you have.", a: "Maya Angelou", c: "creativity" },
  { t: "Do not fear mistakes. There are none.", a: "Miles Davis", c: "creativity" },
  { t: "An idea that is not dangerous is unworthy of being called an idea at all.", a: "Oscar Wilde", c: "creativity" },
  { t: "Art is the most intense mode of individualism that the world has known.", a: "Oscar Wilde", c: "creativity" },
  { t: "Art is the lie that enables us to realize the truth.", a: "Pablo Picasso", c: "creativity" },
  { t: "Everything you can imagine is real.", a: "Pablo Picasso", c: "creativity" },
  { t: "The chief enemy of creativity is good sense.", a: "Pablo Picasso", c: "creativity" },
  { t: "Do not be too timid and squeamish about your actions. All life is an experiment.", a: "Ralph Waldo Emerson", c: "creativity" },
  { t: "Every artist was first an amateur.", a: "Ralph Waldo Emerson", c: "creativity" },
  { t: "Let yourself be silently drawn by the strange pull of what you really love.", a: "Rumi", c: "creativity" },
  { t: "Respond to every call that excites your spirit.", a: "Rumi", c: "creativity" },
  { t: "Have no fear of perfection, you'll never reach it.", a: "Salvador Dali", c: "creativity" },
  { t: "All art is but imitation of nature.", a: "Seneca", c: "creativity" },
  { t: "Education is the kindling of a flame, not the filling of a vessel.", a: "Socrates", c: "creativity" },
  { t: "Design is not just what it looks like and feels like. Design is how it works.", a: "Steve Jobs", c: "creativity" },
  { t: "The worst enemy to creativity is self-doubt.", a: "Sylvia Plath", c: "creativity" },

  // -- GRIT ----------------------------------------------------------------
  { t: "It's not that I'm so smart, it's just that I stay with problems longer.", a: "Albert Einstein", c: "grit" },
  { t: "Life is like riding a bicycle. To keep your balance, you must keep moving.", a: "Albert Einstein", c: "grit" },
  { t: "Patience is bitter, but its fruit is sweet.", a: "Aristotle", c: "grit" },
  { t: "Energy and persistence conquer all things.", a: "Benjamin Franklin", c: "grit" },
  { t: "Hardships often prepare ordinary people for an extraordinary destiny.", a: "C. S. Lewis", c: "grit" },
  { t: "He who conquers himself is the mightiest warrior.", a: "Confucius", c: "grit" },
  { t: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius", c: "grit" },
  { t: "Our greatest glory is not in never failing, but in rising every time we fall.", a: "Confucius", c: "grit" },
  { t: "Do the hard jobs first. The easy jobs will take care of themselves.", a: "Dale Carnegie", c: "grit" },
  { t: "Difficulties show a man what he is.", a: "Epictetus", c: "grit" },
  { t: "Never confuse a single defeat with a final defeat.", a: "F. Scott Fitzgerald", c: "grit" },
  { t: "That which does not kill us makes us stronger.", a: "Friedrich Nietzsche", c: "grit" },
  { t: "The snake which cannot cast its skin has to die.", a: "Friedrich Nietzsche", c: "grit" },
  { t: "Rock bottom became the solid foundation on which I rebuilt my life.", a: "J. K. Rowling", c: "grit" },
  { t: "A river cuts through rock not because of its power, but because of its persistence.", a: "James N. Watkins", c: "grit" },
  { t: "Fall seven times, stand up eight.", a: "Japanese Proverb", c: "grit" },
  { t: "Water is fluid, soft and yielding. But water will wear away rock, which is rigid and cannot yield.", a: "Lao Tzu", c: "grit" },
  { t: "The best revenge is to be unlike him who performed the injury.", a: "Marcus Aurelius", c: "grit" },
  { t: "You could leave life right now. Let that determine what you do and say and think.", a: "Marcus Aurelius", c: "grit" },
  { t: "You may have to fight a battle more than once to win it.", a: "Margaret Thatcher", c: "grit" },
  { t: "Continuous improvement is better than delayed perfection.", a: "Mark Twain", c: "grit" },
  { t: "Courage is resistance to fear, mastery of fear — not absence of fear.", a: "Mark Twain", c: "grit" },
  { t: "Courage doesn't always roar. Sometimes it is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", a: "Mary Anne Radmacher", c: "grit" },
  { t: "I can be changed by what happens to me. But I refuse to be reduced by it.", a: "Maya Angelou", c: "grit" },
  { t: "To live is the rarest thing in the world. Most people exist, that is all.", a: "Oscar Wilde", c: "grit" },
  { t: "Do the thing and you will have the power.", a: "Ralph Waldo Emerson", c: "grit" },
  { t: "That which we persist in doing becomes easier — not that the nature of the task has changed, but our ability to do has increased.", a: "Ralph Waldo Emerson", c: "grit" },
  { t: "The only way out is through.", a: "Robert Frost", c: "grit" },
  { t: "The struggle you're in today is developing the strength you need for tomorrow.", a: "Robert Tew", c: "grit" },
  { t: "Don't grieve. Anything you lose comes round in another form.", a: "Rumi", c: "grit" },
  { t: "Where there is ruin, there is hope for a treasure.", a: "Rumi", c: "grit" },
  { t: "A gem cannot be polished without friction, nor a man perfected without trials.", a: "Seneca", c: "grit" },
  { t: "Sometimes even to live is an act of courage.", a: "Seneca", c: "grit" },
  { t: "If you're going through hell, keep going.", a: "Winston Churchill", c: "grit" },
  { t: "Success is not final, failure is not fatal: it is the courage to continue that counts.", a: "Winston Churchill", c: "grit" }
];
