/* ============================================================================
   LUCID — QUOTE LIBRARY
   ----------------------------------------------------------------------------
   THIS IS THE ONLY FILE YOU NEED TO EDIT TO ADD QUOTES.
   Edit it from your phone: open the repo in the GitHub app, tap this file,
   tap the pencil, add a line, commit. The site redeploys in about 40 seconds.

   Format - one object per quote. A quote can belong to SEVERAL categories:

     { t: "The quote text.", a: "Author Name", c: ["wisdom", "time"] }

   A plain string still works if a quote only fits one:

     { t: "...", a: "...", c: "humor" }

   Valid categories:
     inspiration - stoic - wisdom - grit - creativity - humor
     time - love - doubt - solitude

   Rules of thumb:
     - Keep `t` under ~200 characters so it looks great on a phone.
     - The thinker dropdown builds itself from `a`, scoped to the category
       you're on. To make a thinker worth filtering to, give them several
       quotes across a few categories.
     - Multi-tagging is free: a quote tagged ["stoic","time"] shows up in both.

   ON ATTRIBUTION - please keep to these two rules:
     1. Don't invent quotes, and don't force a thinker into a category they
        never spoke to. A gap is better than a fake.
     2. For TRANSLATED authors, the translation carries its own copyright even
        when the author is ancient. The famous English Rumi lines are Coleman
        Barks's "versions" (c) 1995, not Rumi's words - which is why Rumi isn't
        here. Prefer authors who wrote in English, or pre-1930 translations.
        (As of 2026, US works published 1930 or earlier are public domain.)
   ========================================================================== */

window.QUOTES = [
  // -- INSPIRATION -------------------------------------------------------
  { t: "Learn from yesterday, live for today, hope for tomorrow.", a: "Albert Einstein", c: "inspiration" },
  { t: "Happiness depends upon ourselves.", a: "Aristotle", c: "inspiration" },
  { t: "Hope is a waking dream.", a: "Aristotle", c: "inspiration" },
  { t: "Start where you are. Use what you have. Do what you can.", a: "Arthur Ashe", c: "inspiration" },
  { t: "Nothing is impossible. The word itself says 'I'm possible.'", a: "Audrey Hepburn", c: "inspiration" },
  { t: "The best time to plant a tree was twenty years ago. The second best time is now.", a: "Chinese Proverb", c: "inspiration" },
  { t: "While there's life, there's hope.", a: "Cicero", c: ["inspiration", "doubt"] },
  { t: "Choose a job you love, and you will never have to work a day in your life.", a: "Confucius", c: "inspiration" },
  { t: "Everything has beauty, but not everyone sees it.", a: "Confucius", c: "inspiration" },
  { t: "Wherever you go, go with all your heart.", a: "Confucius", c: "inspiration" },
  { t: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt", c: "inspiration" },
  { t: "Light tomorrow with today.", a: "Elizabeth Barrett Browning", c: "inspiration" },
  { t: "Hope is the thing with feathers that perches in the soul.", a: "Emily Dickinson", c: ["inspiration", "doubt"] },
  { t: "If you want to improve, be content to be thought foolish and stupid.", a: "Epictetus", c: "inspiration" },
  { t: "Make the best use of what is in your power, and take the rest as it happens.", a: "Epictetus", c: "inspiration" },
  { t: "The only limit to our realization of tomorrow is our doubts of today.", a: "Franklin D. Roosevelt", c: ["inspiration", "doubt"] },
  { t: "I prefer to be true to myself, even at the hazard of incurring the ridicule of others.", a: "Frederick Douglass", c: ["inspiration", "doubt"] },
  { t: "Once you learn to read, you will be forever free.", a: "Frederick Douglass", c: ["inspiration", "wisdom"] },
  { t: "Become who you are.", a: "Friedrich Nietzsche", c: "inspiration" },
  { t: "He who would learn to fly one day must first learn to stand and walk and run and climb and dance.", a: "Friedrich Nietzsche", c: "inspiration" },
  { t: "Everything you've ever wanted is on the other side of fear.", a: "George Addair", c: ["inspiration", "doubt"] },
  { t: "It is never too late to be what you might have been.", a: "George Eliot", c: ["inspiration", "time"] },
  { t: "Keep your face to the sunshine and you cannot see a shadow.", a: "Helen Keller", c: "inspiration" },
  { t: "Life is either a daring adventure or nothing at all.", a: "Helen Keller", c: ["inspiration", "grit"] },
  { t: "Go confidently in the direction of your dreams. Live the life you have imagined.", a: "Henry David Thoreau", c: "inspiration" },
  { t: "If a man does not keep pace with his companions, perhaps it is because he hears a different drummer.", a: "Henry David Thoreau", c: ["inspiration", "solitude"] },
  { t: "What you get by achieving your goals is not as important as what you become.", a: "Henry David Thoreau", c: "inspiration" },
  { t: "Whether you think you can or you think you can't, you're right.", a: "Henry Ford", c: "inspiration" },
  { t: "I declare after all there is no enjoyment like reading!", a: "Jane Austen", c: ["inspiration", "solitude"] },
  { t: "Someday is not a day of the week.", a: "Janet Dailey", c: ["inspiration", "time"] },
  { t: "A ship in harbor is safe, but that is not what ships are built for.", a: "John A. Shedd", c: "inspiration" },
  { t: "Trust in dreams, for in them is hidden the gate to eternity.", a: "Kahlil Gibran", c: "inspiration" },
  { t: "A good traveler has no fixed plans and is not intent on arriving.", a: "Lao Tzu", c: "inspiration" },
  { t: "Be content with what you have; rejoice in the way things are.", a: "Lao Tzu", c: "inspiration" },
  { t: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", a: "Marcus Aurelius", c: "inspiration" },
  { t: "When you arise in the morning, think of what a precious privilege it is to be alive.", a: "Marcus Aurelius", c: "inspiration" },
  { t: "Keep away from people who try to belittle your ambitions.", a: "Mark Twain", c: "inspiration" },
  { t: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", a: "Mark Twain", c: ["inspiration", "time"] },
  { t: "It always seems impossible until it's done.", a: "Nelson Mandela", c: ["inspiration", "doubt"] },
  { t: "There is no passion to be found in settling for a life that is less than the one you are capable of living.", a: "Nelson Mandela", c: "inspiration" },
  { t: "Be yourself; everyone else is already taken.", a: "Oscar Wilde", c: "inspiration" },
  { t: "We are all in the gutter, but some of us are looking at the stars.", a: "Oscar Wilde", c: "inspiration" },
  { t: "Do not go where the path may lead; go instead where there is no path and leave a trail.", a: "Ralph Waldo Emerson", c: "inspiration" },
  { t: "Nothing great was ever achieved without enthusiasm.", a: "Ralph Waldo Emerson", c: "inspiration" },
  { t: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", a: "Ralph Waldo Emerson", c: "inspiration" },
  { t: "Write it on your heart that every day is the best day in the year.", a: "Ralph Waldo Emerson", c: "inspiration" },
  { t: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.", a: "Seneca", c: "inspiration" },
  { t: "Life is long if you know how to use it.", a: "Seneca", c: ["inspiration", "time"] },
  { t: "Employ your time in improving yourself by other men's writings, so that you shall gain easily what others have labored hard for.", a: "Socrates", c: "inspiration" },
  { t: "Let him that would move the world first move himself.", a: "Socrates", c: "inspiration" },
  { t: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs", c: ["inspiration", "time"] },
  { t: "Believe you can and you're halfway there.", a: "Theodore Roosevelt", c: ["inspiration", "doubt"] },
  { t: "I would rather die of passion than of boredom.", a: "Vincent van Gogh", c: "inspiration" },
  { t: "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.", a: "Virginia Woolf", c: ["inspiration", "creativity"] },
  { t: "I celebrate myself, and sing myself.", a: "Walt Whitman", c: "inspiration" },
  { t: "Keep your face always toward the sunshine, and shadows will fall behind you.", a: "Walt Whitman", c: ["inspiration", "doubt"] },
  { t: "The powerful play goes on, and you may contribute a verse.", a: "Walt Whitman", c: ["inspiration", "time"] },
  { t: "You miss one hundred percent of the shots you don't take.", a: "Wayne Gretzky", c: "inspiration" },
  { t: "Act as if what you do makes a difference. It does.", a: "William James", c: "inspiration" },
  { t: "What you get by achieving your goals is not as important as what you become by achieving them.", a: "Zig Ziglar", c: "inspiration" },

  // -- STOIC -------------------------------------------------------------
  { t: "First say to yourself what you would be; and then do what you have to do.", a: "Epictetus", c: "stoic" },
  { t: "How long are you going to wait before you demand the best for yourself?", a: "Epictetus", c: ["stoic", "time"] },
  { t: "It's not what happens to you, but how you react to it that matters.", a: "Epictetus", c: "stoic" },
  { t: "Man is not worried by real problems so much as by his imagined anxieties about real problems.", a: "Epictetus", c: ["stoic", "doubt"] },
  { t: "No man is free who is not master of himself.", a: "Epictetus", c: ["stoic", "solitude"] },
  { t: "Wealth consists not in having great possessions, but in having few wants.", a: "Epictetus", c: ["stoic", "solitude"] },
  { t: "Confine yourself to the present.", a: "Marcus Aurelius", c: ["stoic", "time"] },
  { t: "If it is not right, do not do it. If it is not true, do not say it.", a: "Marcus Aurelius", c: "stoic" },
  { t: "The happiness of your life depends upon the quality of your thoughts.", a: "Marcus Aurelius", c: "stoic" },
  { t: "The impediment to action advances action. What stands in the way becomes the way.", a: "Marcus Aurelius", c: "stoic" },
  { t: "Waste no more time arguing about what a good man should be. Be one.", a: "Marcus Aurelius", c: "stoic" },
  { t: "You have power over your mind, not outside events. Realize this, and you will find strength.", a: "Marcus Aurelius", c: "stoic" },
  { t: "Begin at once to live, and count each separate day as a separate life.", a: "Seneca", c: ["stoic", "time"] },
  { t: "Difficulties strengthen the mind, as labor does the body.", a: "Seneca", c: "stoic" },
  { t: "He who fears death will never do anything worthy of a man who is alive.", a: "Seneca", c: ["stoic", "time", "doubt"] },
  { t: "It is not that we have a short time to live, but that we waste a lot of it.", a: "Seneca", c: ["stoic", "time"] },
  { t: "Luck is what happens when preparation meets opportunity.", a: "Seneca", c: "stoic" },
  { t: "We suffer more often in imagination than in reality.", a: "Seneca", c: ["stoic", "doubt"] },

  // -- WISDOM ------------------------------------------------------------
  { t: "In the middle of difficulty lies opportunity.", a: "Albert Einstein", c: "wisdom" },
  { t: "The important thing is not to stop questioning.", a: "Albert Einstein", c: "wisdom" },
  { t: "Try not to become a man of success, but rather try to become a man of value.", a: "Albert Einstein", c: "wisdom" },
  { t: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", a: "Aristotle", c: "wisdom" },
  { t: "Knowing yourself is the beginning of all wisdom.", a: "Aristotle", c: "wisdom" },
  { t: "The whole is greater than the sum of its parts.", a: "Aristotle", c: "wisdom" },
  { t: "An investment in knowledge pays the best interest.", a: "Benjamin Franklin", c: "wisdom" },
  { t: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", a: "Benjamin Franklin", c: "wisdom" },
  { t: "There never was a good war or a bad peace.", a: "Benjamin Franklin", c: "wisdom" },
  { t: "Well done is better than well said.", a: "Benjamin Franklin", c: ["wisdom", "creativity"] },
  { t: "Man is but a reed, the weakest in nature, but he is a thinking reed.", a: "Blaise Pascal", c: ["wisdom", "doubt"] },
  { t: "Small minds are concerned with the extraordinary, great minds with the ordinary.", a: "Blaise Pascal", c: "wisdom" },
  { t: "We are usually convinced more easily by reasons we have found ourselves than by those which have occurred to others.", a: "Blaise Pascal", c: "wisdom" },
  { t: "Any man can make mistakes, but only an idiot persists in his error.", a: "Cicero", c: ["wisdom", "humor"] },
  { t: "Nobody can give you wiser advice than yourself.", a: "Cicero", c: ["wisdom", "solitude"] },
  { t: "The wise are instructed by reason; ordinary minds by experience; the stupid, by necessity.", a: "Cicero", c: "wisdom" },
  { t: "Before you embark on a journey of revenge, dig two graves.", a: "Confucius", c: "wisdom" },
  { t: "Real knowledge is to know the extent of one's ignorance.", a: "Confucius", c: "wisdom" },
  { t: "The man who moves a mountain begins by carrying away small stones.", a: "Confucius", c: "wisdom" },
  { t: "Only the educated are free.", a: "Epictetus", c: "wisdom" },
  { t: "We have two ears and one mouth, so that we can listen twice as much as we speak.", a: "Epictetus", c: "wisdom" },
  { t: "Do not spoil what you have by desiring what you have not.", a: "Epicurus", c: ["wisdom", "solitude"] },
  { t: "He who is not satisfied with a little is satisfied with nothing.", a: "Epicurus", c: "wisdom" },
  { t: "Not what we have but what we enjoy constitutes our abundance.", a: "Epicurus", c: "wisdom" },
  { t: "A little learning, indeed, may be a dangerous thing, but the want of learning is a calamity to any people.", a: "Frederick Douglass", c: "wisdom" },
  { t: "I would unite with anybody to do right and with nobody to do wrong.", a: "Frederick Douglass", c: ["wisdom", "grit"] },
  { t: "It is easier to build strong children than to repair broken men.", a: "Frederick Douglass", c: "wisdom" },
  { t: "He who has a why to live can bear almost any how.", a: "Friedrich Nietzsche", c: "wisdom" },
  { t: "The higher we soar, the smaller we appear to those who cannot fly.", a: "Friedrich Nietzsche", c: "wisdom" },
  { t: "There are no facts, only interpretations.", a: "Friedrich Nietzsche", c: "wisdom" },
  { t: "It is a narrow mind which cannot look at a subject from various points of view.", a: "George Eliot", c: "wisdom" },
  { t: "The only thing worse than being blind is having sight but no vision.", a: "Helen Keller", c: ["wisdom", "creativity"] },
  { t: "Rather than love, than money, than fame, give me truth.", a: "Henry David Thoreau", c: "wisdom" },
  { t: "The mass of men lead lives of quiet desperation.", a: "Henry David Thoreau", c: ["wisdom", "doubt"] },
  { t: "Things do not change; we change.", a: "Henry David Thoreau", c: ["wisdom", "time"] },
  { t: "Character is destiny.", a: "Heraclitus", c: "wisdom" },
  { t: "Much learning does not teach understanding.", a: "Heraclitus", c: "wisdom" },
  { t: "The road up and the road down are the same thing.", a: "Heraclitus", c: "wisdom" },
  { t: "Angry people are not always wise.", a: "Jane Austen", c: "wisdom" },
  { t: "Vanity and pride are different things, though the words are often used synonymously.", a: "Jane Austen", c: "wisdom" },
  { t: "Your joy is your sorrow unmasked. The deeper that sorrow carves into your being, the more joy you can contain.", a: "Kahlil Gibran", c: ["wisdom", "doubt"] },
  { t: "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.", a: "Lao Tzu", c: "wisdom" },
  { t: "Nature does not hurry, yet everything is accomplished.", a: "Lao Tzu", c: ["wisdom", "time", "solitude"] },
  { t: "Silence is a source of great strength.", a: "Lao Tzu", c: ["wisdom", "solitude"] },
  { t: "The journey of a thousand miles begins with a single step.", a: "Lao Tzu", c: "wisdom" },
  { t: "To attain knowledge, add things every day. To attain wisdom, subtract things every day.", a: "Lao Tzu", c: ["wisdom", "solitude"] },
  { t: "When I let go of what I am, I become what I might be.", a: "Lao Tzu", c: ["wisdom", "doubt"] },
  { t: "Simplicity is the ultimate sophistication.", a: "Leonardo da Vinci", c: "wisdom" },
  { t: "Be the change that you wish to see in the world.", a: "Mahatma Gandhi", c: "wisdom" },
  { t: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", a: "Marcus Aurelius", c: "wisdom" },
  { t: "The soul becomes dyed with the color of its thoughts.", a: "Marcus Aurelius", c: "wisdom" },
  { t: "Kindness is the language which the deaf can hear and the blind can see.", a: "Mark Twain", c: "wisdom" },
  { t: "The two most important days in your life are the day you are born and the day you find out why.", a: "Mark Twain", c: ["wisdom", "time"] },
  { t: "Let us permit nature to have her way: she understands her business better than we do.", a: "Michel de Montaigne", c: ["wisdom", "solitude"] },
  { t: "Nothing fixes a thing so intensely in the memory as the wish to forget it.", a: "Michel de Montaigne", c: "wisdom" },
  { t: "The most certain sign of wisdom is cheerfulness.", a: "Michel de Montaigne", c: ["wisdom", "humor"] },
  { t: "Turn your wounds into wisdom.", a: "Oprah Winfrey", c: "wisdom" },
  { t: "Experience is simply the name we give our mistakes.", a: "Oscar Wilde", c: "wisdom" },
  { t: "The truth is rarely pure and never simple.", a: "Oscar Wilde", c: "wisdom" },
  { t: "The only person you are destined to become is the person you decide to be.", a: "Ralph Waldo Emerson", c: "wisdom" },
  { t: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", a: "Ralph Waldo Emerson", c: "wisdom" },
  { t: "As long as you live, keep learning how to live.", a: "Seneca", c: ["wisdom", "time"] },
  { t: "Every new beginning comes from some other beginning's end.", a: "Seneca", c: ["wisdom", "time"] },
  { t: "Be as you wish to seem.", a: "Socrates", c: "wisdom" },
  { t: "The only true wisdom is in knowing you know nothing.", a: "Socrates", c: "wisdom" },
  { t: "The unexamined life is not worth living.", a: "Socrates", c: "wisdom" },
  { t: "Wonder is the beginning of wisdom.", a: "Socrates", c: "wisdom" },
  { t: "For most of history, Anonymous was a woman.", a: "Virginia Woolf", c: ["wisdom", "humor"] },
  { t: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Will Durant", c: "wisdom" },

  // -- GRIT --------------------------------------------------------------
  { t: "It's not that I'm so smart, it's just that I stay with problems longer.", a: "Albert Einstein", c: "grit" },
  { t: "Life is like riding a bicycle. To keep your balance, you must keep moving.", a: "Albert Einstein", c: "grit" },
  { t: "Patience is bitter, but its fruit is sweet.", a: "Aristotle", c: "grit" },
  { t: "By failing to prepare, you are preparing to fail.", a: "Benjamin Franklin", c: "grit" },
  { t: "Energy and persistence conquer all things.", a: "Benjamin Franklin", c: "grit" },
  { t: "He that can have patience can have what he will.", a: "Benjamin Franklin", c: ["grit", "time"] },
  { t: "Hardships often prepare ordinary people for an extraordinary destiny.", a: "C. S. Lewis", c: "grit" },
  { t: "He who conquers himself is the mightiest warrior.", a: "Confucius", c: "grit" },
  { t: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius", c: "grit" },
  { t: "Our greatest glory is not in never failing, but in rising every time we fall.", a: "Confucius", c: "grit" },
  { t: "Do the hard jobs first. The easy jobs will take care of themselves.", a: "Dale Carnegie", c: "grit" },
  { t: "Difficulties show a man what he is.", a: "Epictetus", c: "grit" },
  { t: "Never confuse a single defeat with a final defeat.", a: "F. Scott Fitzgerald", c: "grit" },
  { t: "If there is no struggle, there is no progress.", a: "Frederick Douglass", c: "grit" },
  { t: "Power concedes nothing without a demand. It never did and it never will.", a: "Frederick Douglass", c: "grit" },
  { t: "The limits of tyrants are prescribed by the endurance of those whom they oppress.", a: "Frederick Douglass", c: "grit" },
  { t: "That which does not kill us makes us stronger.", a: "Friedrich Nietzsche", c: "grit" },
  { t: "The snake which cannot cast its skin has to die.", a: "Friedrich Nietzsche", c: "grit" },
  { t: "The strongest principle of growth lies in the human choice.", a: "George Eliot", c: "grit" },
  { t: "Although the world is full of suffering, it is also full of the overcoming of it.", a: "Helen Keller", c: ["grit", "doubt"] },
  { t: "Big results require big ambitions.", a: "Heraclitus", c: ["grit", "inspiration"] },
  { t: "Rock bottom became the solid foundation on which I rebuilt my life.", a: "J. K. Rowling", c: ["grit", "doubt"] },
  { t: "A river cuts through rock not because of its power, but because of its persistence.", a: "James N. Watkins", c: "grit" },
  { t: "Fall seven times, stand up eight.", a: "Japanese Proverb", c: "grit" },
  { t: "Out of suffering have emerged the strongest souls.", a: "Kahlil Gibran", c: ["grit", "doubt"] },
  { t: "Water is fluid, soft and yielding. But water will wear away rock, which is rigid and cannot yield.", a: "Lao Tzu", c: "grit" },
  { t: "The best revenge is to be unlike him who performed the injury.", a: "Marcus Aurelius", c: "grit" },
  { t: "You could leave life right now. Let that determine what you do and say and think.", a: "Marcus Aurelius", c: ["grit", "time"] },
  { t: "You may have to fight a battle more than once to win it.", a: "Margaret Thatcher", c: "grit" },
  { t: "Continuous improvement is better than delayed perfection.", a: "Mark Twain", c: "grit" },
  { t: "Courage is resistance to fear, mastery of fear — not absence of fear.", a: "Mark Twain", c: ["grit", "doubt"] },
  { t: "Courage doesn't always roar. Sometimes it is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", a: "Mary Anne Radmacher", c: "grit" },
  { t: "I can be changed by what happens to me. But I refuse to be reduced by it.", a: "Maya Angelou", c: "grit" },
  { t: "To live is the rarest thing in the world. Most people exist, that is all.", a: "Oscar Wilde", c: "grit" },
  { t: "Do the thing and you will have the power.", a: "Ralph Waldo Emerson", c: "grit" },
  { t: "That which we persist in doing becomes easier — not that the nature of the task has changed, but our ability to do has increased.", a: "Ralph Waldo Emerson", c: "grit" },
  { t: "The only way out is through.", a: "Robert Frost", c: "grit" },
  { t: "The struggle you're in today is developing the strength you need for tomorrow.", a: "Robert Tew", c: "grit" },
  { t: "A gem cannot be polished without friction, nor a man perfected without trials.", a: "Seneca", c: "grit" },
  { t: "Sometimes even to live is an act of courage.", a: "Seneca", c: "grit" },
  { t: "The fishermen know that the sea is dangerous and the storm terrible, but they have never found these dangers sufficient reason for remaining ashore.", a: "Vincent van Gogh", c: ["grit", "doubt"] },
  { t: "Resist much, obey little.", a: "Walt Whitman", c: ["grit", "inspiration"] },
  { t: "If you're going through hell, keep going.", a: "Winston Churchill", c: "grit" },
  { t: "Success is not final, failure is not fatal: it is the courage to continue that counts.", a: "Winston Churchill", c: "grit" },

  // -- CREATIVITY --------------------------------------------------------
  { t: "Creativity is intelligence having fun.", a: "Albert Einstein", c: "creativity" },
  { t: "Imagination is more important than knowledge.", a: "Albert Einstein", c: "creativity" },
  { t: "Logic will get you from A to B. Imagination will take you everywhere.", a: "Albert Einstein", c: "creativity" },
  { t: "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", a: "Antoine de Saint-Exupery", c: "creativity" },
  { t: "The aim of art is to represent not the outward appearance of things, but their inward significance.", a: "Aristotle", c: "creativity" },
  { t: "Either write something worth reading or do something worth writing.", a: "Benjamin Franklin", c: ["creativity", "inspiration"] },
  { t: "I hear and I forget. I see and I remember. I do and I understand.", a: "Confucius", c: "creativity" },
  { t: "The desire to create is one of the deepest yearnings of the human soul.", a: "Dieter F. Uchtdorf", c: "creativity" },
  { t: "Dwell in possibility.", a: "Emily Dickinson", c: ["creativity", "inspiration"] },
  { t: "One must still have chaos in oneself to be able to give birth to a dancing star.", a: "Friedrich Nietzsche", c: "creativity" },
  { t: "We have art in order not to die of the truth.", a: "Friedrich Nietzsche", c: "creativity" },
  { t: "You can't wait for inspiration. You have to go after it with a club.", a: "Jack London", c: "creativity" },
  { t: "Vision is the art of seeing what is invisible to others.", a: "Jonathan Swift", c: "creativity" },
  { t: "To live a creative life, we must lose our fear of being wrong.", a: "Joseph Chilton Pearce", c: ["creativity", "doubt"] },
  { t: "Work is love made visible.", a: "Kahlil Gibran", c: ["creativity", "love"] },
  { t: "Great acts are made up of small deeds.", a: "Lao Tzu", c: "creativity" },
  { t: "The usefulness of a pot comes from its emptiness.", a: "Lao Tzu", c: "creativity" },
  { t: "The secret of getting ahead is getting started.", a: "Mark Twain", c: "creativity" },
  { t: "You can't use up creativity. The more you use, the more you have.", a: "Maya Angelou", c: "creativity" },
  { t: "Do not fear mistakes. There are none.", a: "Miles Davis", c: "creativity" },
  { t: "An idea that is not dangerous is unworthy of being called an idea at all.", a: "Oscar Wilde", c: "creativity" },
  { t: "Art is the most intense mode of individualism that the world has known.", a: "Oscar Wilde", c: "creativity" },
  { t: "Art is the lie that enables us to realize the truth.", a: "Pablo Picasso", c: "creativity" },
  { t: "Everything you can imagine is real.", a: "Pablo Picasso", c: "creativity" },
  { t: "The chief enemy of creativity is good sense.", a: "Pablo Picasso", c: "creativity" },
  { t: "Do not be too timid and squeamish about your actions. All life is an experiment.", a: "Ralph Waldo Emerson", c: "creativity" },
  { t: "Every artist was first an amateur.", a: "Ralph Waldo Emerson", c: "creativity" },
  { t: "Have no fear of perfection, you'll never reach it.", a: "Salvador Dali", c: ["creativity", "doubt"] },
  { t: "All art is but imitation of nature.", a: "Seneca", c: "creativity" },
  { t: "Education is the kindling of a flame, not the filling of a vessel.", a: "Socrates", c: "creativity" },
  { t: "Design is not just what it looks like and feels like. Design is how it works.", a: "Steve Jobs", c: "creativity" },
  { t: "The worst enemy to creativity is self-doubt.", a: "Sylvia Plath", c: ["creativity", "doubt"] },
  { t: "Do not quench your inspiration and your imagination.", a: "Vincent van Gogh", c: "creativity" },
  { t: "Great things are not done by impulse, but by a series of small things brought together.", a: "Vincent van Gogh", c: ["creativity", "grit"] },
  { t: "I am seeking, I am striving, I am in it with all my heart.", a: "Vincent van Gogh", c: ["creativity", "grit"] },
  { t: "I dream my painting and I paint my dream.", a: "Vincent van Gogh", c: "creativity" },
  { t: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", a: "Vincent van Gogh", c: ["creativity", "doubt"] },
  { t: "Normality is a paved road: it is comfortable to walk, but no flowers grow on it.", a: "Vincent van Gogh", c: ["creativity", "inspiration"] },
  { t: "A woman must have money and a room of her own if she is to write fiction.", a: "Virginia Woolf", c: ["creativity", "solitude"] },

  // -- HUMOR -------------------------------------------------------------
  { t: "People say nothing is impossible, but I do nothing every day.", a: "A. A. Milne", c: "humor" },
  { t: "If you can't explain it simply, you don't understand it well enough.", a: "Albert Einstein", c: "humor" },
  { t: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", a: "Albert Einstein", c: "humor" },
  { t: "The gods too are fond of a joke.", a: "Aristotle", c: "humor" },
  { t: "I have made this letter longer than usual because I have not had time to make it shorter.", a: "Blaise Pascal", c: ["humor", "creativity"] },
  { t: "If you think you are too small to make a difference, try sleeping with a mosquito.", a: "Dalai Lama", c: "humor" },
  { t: "Do not take life too seriously. You will never get out of it alive.", a: "Elbert Hubbard", c: ["humor", "time"] },
  { t: "Without music, life would be a mistake.", a: "Friedrich Nietzsche", c: "humor" },
  { t: "It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.", a: "Jane Austen", c: ["humor", "love"] },
  { t: "Nobody minds having what is too good for them.", a: "Jane Austen", c: "humor" },
  { t: "One half of the world cannot understand the pleasures of the other.", a: "Jane Austen", c: ["humor", "wisdom"] },
  { t: "I always wanted to be somebody, but now I realize I should have been more specific.", a: "Lily Tomlin", c: "humor" },
  { t: "Age is an issue of mind over matter. If you don't mind, it doesn't matter.", a: "Mark Twain", c: ["humor", "time"] },
  { t: "Get your facts first, then you can distort them as you please.", a: "Mark Twain", c: "humor" },
  { t: "It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt.", a: "Mark Twain", c: "humor" },
  { t: "The reports of my death are greatly exaggerated.", a: "Mark Twain", c: "humor" },
  { t: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", a: "Mark Twain", c: "humor" },
  { t: "On the highest throne in the world, we still sit only on our own bottom.", a: "Michel de Montaigne", c: ["humor", "wisdom"] },
  { t: "There is no conversation more boring than the one where everybody agrees.", a: "Michel de Montaigne", c: ["humor", "wisdom"] },
  { t: "Always borrow money from a pessimist. He won't expect it back.", a: "Oscar Wilde", c: "humor" },
  { t: "I am so clever that sometimes I don't understand a single word of what I am saying.", a: "Oscar Wilde", c: "humor" },
  { t: "I can resist everything except temptation.", a: "Oscar Wilde", c: "humor" },
  { t: "Some cause happiness wherever they go; others whenever they go.", a: "Oscar Wilde", c: "humor" },
  { t: "The louder he talked of his honor, the faster we counted our spoons.", a: "Ralph Waldo Emerson", c: "humor" },
  { t: "I know that I am intelligent, because I know that I know nothing.", a: "Socrates", c: "humor" },
  { t: "My advice to you is get married: if you find a good wife you'll be happy; if not, you'll become a philosopher.", a: "Socrates", c: "humor" },
  { t: "A day without sunshine is like, you know, night.", a: "Steve Martin", c: "humor" },
  { t: "I'm writing a book. I've got the page numbers done.", a: "Steven Wright", c: "humor" },
  { t: "The trouble with having an open mind is that people keep coming along and sticking things into it.", a: "Terry Pratchett", c: "humor" },
  { t: "I have not failed. I've just found ten thousand ways that won't work.", a: "Thomas Edison", c: "humor" },
  { t: "The early bird gets the worm, but the second mouse gets the cheese.", a: "Unknown", c: "humor" },
  { t: "One cannot think well, love well, sleep well, if one has not dined well.", a: "Virginia Woolf", c: ["humor", "wisdom"] },
  { t: "Everything is funny, as long as it's happening to somebody else.", a: "Will Rogers", c: "humor" },
  { t: "The road to success is dotted with many tempting parking spaces.", a: "Will Rogers", c: "humor" },

  // -- TIME & MORTALITY --------------------------------------------------
  { t: "Do not put off till tomorrow what can be done today.", a: "Benjamin Franklin", c: ["time", "grit"] },
  { t: "Dost thou love life? Then do not squander time, for that is the stuff life is made of.", a: "Benjamin Franklin", c: "time" },
  { t: "Lost time is never found again.", a: "Benjamin Franklin", c: "time" },
  { t: "Many people die at twenty five and aren't buried until they are seventy five.", a: "Benjamin Franklin", c: ["time", "humor"] },
  { t: "The life of the dead is placed in the memory of the living.", a: "Cicero", c: ["time", "love"] },
  { t: "Because I could not stop for Death, he kindly stopped for me.", a: "Emily Dickinson", c: "time" },
  { t: "Forever is composed of nows.", a: "Emily Dickinson", c: "time" },
  { t: "That it will never come again is what makes life so sweet.", a: "Emily Dickinson", c: "time" },
  { t: "Death is nothing to us; when we exist, death is not; and when death exists, we are not.", a: "Epicurus", c: "time" },
  { t: "We have to do with the past only as we can make it useful to the present and the future.", a: "Frederick Douglass", c: ["time", "wisdom"] },
  { t: "It is not enough to be busy. The question is: what are we busy about?", a: "Henry David Thoreau", c: ["time", "wisdom"] },
  { t: "Live in each season as it passes; breathe the air, drink the drink, taste the fruit.", a: "Henry David Thoreau", c: ["time", "solitude"] },
  { t: "No man ever steps in the same river twice, for it is not the same river and he is not the same man.", a: "Heraclitus", c: ["time", "wisdom"] },
  { t: "Nothing endures but change.", a: "Heraclitus", c: "time" },
  { t: "Yesterday is but today's memory, and tomorrow is today's dream.", a: "Kahlil Gibran", c: "time" },
  { t: "The value of life lies not in the length of days, but in the use we make of them.", a: "Michel de Montaigne", c: "time" },
  { t: "To lament that we shall not be alive a hundred years hence is the same folly as to be sorry we were not alive a hundred years ago.", a: "Michel de Montaigne", c: "time" },
  { t: "Happiness, not in another place but this place; not for another hour, but this hour.", a: "Walt Whitman", c: ["time", "inspiration"] },

  // -- LOVE & FRIENDSHIP -------------------------------------------------
  { t: "Friendship is a single soul dwelling in two bodies.", a: "Aristotle", c: "love" },
  { t: "Kind words do not cost much. Yet they accomplish much.", a: "Blaise Pascal", c: ["love", "wisdom"] },
  { t: "The heart has its reasons which reason knows nothing of.", a: "Blaise Pascal", c: ["love", "wisdom"] },
  { t: "A friend is, as it were, a second self.", a: "Cicero", c: "love" },
  { t: "Friendship makes prosperity more brilliant, and lightens adversity by dividing and sharing it.", a: "Cicero", c: ["love", "grit"] },
  { t: "Life is nothing without friendship.", a: "Cicero", c: "love" },
  { t: "Never contract friendship with a man that is not better than thyself.", a: "Confucius", c: ["love", "wisdom"] },
  { t: "If I can stop one heart from breaking, I shall not live in vain.", a: "Emily Dickinson", c: "love" },
  { t: "My friends are my estate.", a: "Emily Dickinson", c: "love" },
  { t: "It is not so much our friends' help that helps us, as the confident knowledge that they will help us.", a: "Epicurus", c: "love" },
  { t: "Of all the means to insure happiness throughout the whole life, by far the most important is the acquisition of friends.", a: "Epicurus", c: "love" },
  { t: "Blessed is the influence of one true, loving human soul on another.", a: "George Eliot", c: "love" },
  { t: "What do we live for, if it is not to make life less difficult to each other?", a: "George Eliot", c: "love" },
  { t: "Alone we can do so little; together we can do so much.", a: "Helen Keller", c: "love" },
  { t: "The language of friendship is not words but meanings.", a: "Henry David Thoreau", c: "love" },
  { t: "Friendship is certainly the finest balm for the pangs of disappointed love.", a: "Jane Austen", c: "love" },
  { t: "There is no charm equal to tenderness of heart.", a: "Jane Austen", c: "love" },
  { t: "There is nothing I would not do for those who are really my friends.", a: "Jane Austen", c: "love" },
  { t: "In the sweetness of friendship let there be laughter, and sharing of pleasures.", a: "Kahlil Gibran", c: "love" },
  { t: "Let there be spaces in your togetherness.", a: "Kahlil Gibran", c: ["love", "solitude"] },
  { t: "Love one another, but make not a bond of love: let it rather be a moving sea between the shores of your souls.", a: "Kahlil Gibran", c: "love" },
  { t: "You give but little when you give of your possessions. It is when you give of yourself that you truly give.", a: "Kahlil Gibran", c: ["love", "wisdom"] },
  { t: "Your children are not your children. They are the sons and daughters of Life's longing for itself.", a: "Kahlil Gibran", c: ["love", "wisdom"] },
  { t: "Your friend is your needs answered.", a: "Kahlil Gibran", c: "love" },
  { t: "Men exist for the sake of one another.", a: "Marcus Aurelius", c: ["love", "wisdom"] },
  { t: "Grief can take care of itself, but to get the full value of a joy you must have somebody to divide it with.", a: "Mark Twain", c: "love" },
  { t: "Anyone can sympathize with the sufferings of a friend, but it requires a very fine nature to sympathize with a friend's success.", a: "Oscar Wilde", c: ["love", "humor"] },
  { t: "A friend may well be reckoned the masterpiece of nature.", a: "Ralph Waldo Emerson", c: "love" },
  { t: "The only way to have a friend is to be one.", a: "Ralph Waldo Emerson", c: "love" },
  { t: "One of the most beautiful qualities of true friendship is to understand and to be understood.", a: "Seneca", c: "love" },
  { t: "Be slow to fall into friendship; but when thou art in, continue firm and constant.", a: "Socrates", c: "love" },

  // -- DOUBT & FEAR ------------------------------------------------------
  { t: "The eternal silence of these infinite spaces frightens me.", a: "Blaise Pascal", c: ["doubt", "solitude"] },
  { t: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", a: "Helen Keller", c: ["doubt", "inspiration"] },
  { t: "Not until we are lost do we begin to understand ourselves.", a: "Henry David Thoreau", c: ["doubt", "wisdom"] },
  { t: "I have been a selfish being all my life, in practice, though not in principle.", a: "Jane Austen", c: ["doubt", "wisdom"] },
  { t: "Where so many hours have been spent in convincing myself that I am right, is there not some reason to fear I may be wrong?", a: "Jane Austen", c: "doubt" },
  { t: "Doubt is a pain too lonely to know that faith is his twin brother.", a: "Kahlil Gibran", c: "doubt" },
  { t: "He who fears he shall suffer, already suffers what he fears.", a: "Michel de Montaigne", c: "doubt" },
  { t: "My life has been filled with terrible misfortunes, most of which never happened.", a: "Michel de Montaigne", c: ["doubt", "humor"] },
  { t: "What would life be if we had no courage to attempt anything?", a: "Vincent van Gogh", c: ["doubt", "inspiration"] },

  // -- SOLITUDE & STILLNESS ----------------------------------------------
  { t: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", a: "Blaise Pascal", c: "solitude" },
  { t: "Saying nothing sometimes says the most.", a: "Emily Dickinson", c: ["solitude", "wisdom"] },
  { t: "The soul should always stand ajar.", a: "Emily Dickinson", c: ["solitude", "wisdom"] },
  { t: "The wealth required by nature is limited and easy to procure; that required by vain ideals extends to infinity.", a: "Epicurus", c: ["solitude", "wisdom"] },
  { t: "I never found the companion that was so companionable as solitude.", a: "Henry David Thoreau", c: "solitude" },
  { t: "I went to the woods because I wished to live deliberately.", a: "Henry David Thoreau", c: ["solitude", "inspiration"] },
  { t: "Our life is frittered away by detail. Simplify, simplify.", a: "Henry David Thoreau", c: ["solitude", "wisdom"] },
  { t: "The greatest thing in the world is to know how to belong to oneself.", a: "Michel de Montaigne", c: ["solitude", "wisdom"] },
  { t: "There is peace even in the storm.", a: "Vincent van Gogh", c: ["solitude", "grit"] },
  { t: "No need to hurry. No need to sparkle. No need to be anybody but oneself.", a: "Virginia Woolf", c: ["solitude", "inspiration"] },
  { t: "I exist as I am, that is enough.", a: "Walt Whitman", c: ["solitude", "wisdom"] },
  { t: "Not I, nor anyone else can travel that road for you. You must travel it by yourself.", a: "Walt Whitman", c: ["solitude", "grit"] }
];
